### ISSUE TITLE
Oopsy daisy, oowy moowy weewy

### ISSUE THREAD

**Issue by FoHoOV** [Saeedmohammadiha/ausomelang#1]
Nani? 

```diff
  const tokenType = {
    null: /^\s+/, // Whitespace
    NUMBER: /^\d+/, // Numbers
-   IDENTIFIER: /^[a-zA-Z_]\w*/, // Identifiers
+  IDENTIFIER: /^\w+/, // Identifiers
    EQUAL: /^=/,
```

\w includes all characters+numbers+underscore.  Naze kore o suru nodesu ka

**Comment by Saeedmohammadiha** [comment]
dam you man i thought your comment are in the tweb app, i am looking for it in there for 10 minute 
you don't need to read it so carefully :)
i will fix that

**Comment by FoHoOV** [comment]
Oops, I lied. `\w` matches digits as well. your variable names cannot start with digits so this actually makes perfect sense.
